#include "LCD_INTERFACE.h"
#include <util/delay.h>

void LCD_INITALIZE()
{
	DIO_SET_PORT(OUTPUT_PORT, 0xFF);
	DIO_SET_PORT(CONFIG_PORT, 0xFF);
	
	DIO_CLEAR_PIN(CONFIG_PORT, EN_PIN);
	LCD_SEND_CMD(0x33);
	LCD_SEND_CMD(0x32);
	LCD_SEND_CMD(0x28);
	LCD_SEND_CMD(0x0E);
	LCD_SEND_CMD(0x01);
	_delay_ms(2);
}

void LCD_SEND_CMD(u8 cmd)
{
	DIO_CLEAR_PIN(CONFIG_PORT, RS_PIN);
	
	DIO_SET_PORT(OUTPUT_PORT, cmd & 0xF0);
	DIO_SET_PIN(CONFIG_PORT, EN_PIN);
	_delay_ms(1);
	DIO_CLEAR_PIN(CONFIG_PORT, EN_PIN);
	
	DIO_SET_PORT(OUTPUT_PORT, cmd << 4);
	DIO_SET_PIN(CONFIG_PORT, EN_PIN);
	_delay_ms(1);
	DIO_CLEAR_PIN(CONFIG_PORT, EN_PIN);
}

void LCD_SEND_CHAR(u8 character)
{
	DIO_SET_PIN(CONFIG_PORT, RS_PIN);
	
	DIO_SET_PORT(character, cmd & 0xF0);
	DIO_SET_PIN(CONFIG_PORT, EN_PIN);
	_delay_ms(1);
	DIO_CLEAR_PIN(CONFIG_PORT, EN_PIN);
	
	DIO_SET_PORT(OUTPUT_PORT, character << 4);
	DIO_SET_PIN(CONFIG_PORT, EN_PIN);
	_delay_ms(1);
	DIO_CLEAR_PIN(CONFIG_PORT, EN_PIN);
}

LCD_SEND_STRING(char *string)
{
	while (*string != '\0')
	{
		LCD_SEND_CHAR(*string);
		string++;
	}
}